AWSTemplateFormatVersion: "2010-09-09"
Description: ec2 basic settings region Ireland
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0ce71448843cb18a1
      InstanceType: t2.micro
      KeyName: pepe
      SecurityGroups:
        - !Ref PapuSecurityGroupUserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x

          yum update -y && 
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash &&
          . ~/.nvm/nvm.sh &&
          nvm install node &&
          amazon-linux-extras install nginx1 -y
      Tags:
        -
          Key: environment
          Value: dev
        
  PapuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        Description: ssh
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      